# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  rt_config = debug

else ifeq ($(config),release)
  rt_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := rt

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

rt:
ifneq (,$(rt_config))
	@echo "==== Building rt ($(rt_config)) ===="
	@${MAKE} --no-print-directory -C . -f rt.make config=$(rt_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f rt.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   rt"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"